# 6.1 Sourcing Open Data

### This script contains the following points:
#### 1. Import libraries and data set
#### 2. Check the dimensions of the imported dataframe
#### 3. Data Cleaning

#### 1. Import libraries and data set

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os
import statistics

In [2]:
# Path to original data folder

path = r'C:\Users\Mark\_Electric Power Plant Emissions\03 Scripts\Original Data'

In [3]:
# Path to main project folder

path2 = r'C:\Users\Mark\_Electric Power Plant Emissions'

In [4]:
filepaths = [path + '\\' + f for f in os.listdir(path) if f.endswith('.xlsx')]

In [11]:
# Define a function that takes arguments for the folder path and number of rows to skip from the top and bottom

def read_xl_skip_rows(path, skip_rows, skip_footer):
  return pd.read_excel(path, engine='openpyxl', skiprows=skip_rows, skipfooter=skip_footer)

In [12]:
# Retrieve, map, and concatenate all the .xlsx files (first row and last two rows of each file skipped)

df = pd.concat(map(read_xl_skip_rows, filepaths, [1] * len(filepaths), [2] * len(filepaths)), ignore_index=False)

#### 2. Check the dimensions of the imported dataframe

In [13]:
# Ensure nothing looks out of place with the imported dataframe

df.head()

,Plant Code,Year,Plant Name,State,Sector Group,Sector Code,Prime Mover,Fuel Code,Aggregated Fuel Group,Generation (kWh),...,Fuel Consumption for Electric Generation (MMBtu),\n Fuel Consumption for Useful Thermal Output (MMBtu),Quantity of Fuel Consumed,Fuel Units,Tons of CO2 Emissions,Metric Tonnes of CO2 Emissions,NERC Region,Balancing Authority Code,Balancing Authority Name,EIA Balancing Authority Region
0,3,2013,Barry,AL,ELECTRIC POWER,1,CA,NG,GAS,2813479000,...,588611,0,575166,Mcf,3.443374e+04,3.123809e+04,NaN,NaN,NaN,NaN
1,3,2013,Barry,AL,ELECTRIC POWER,1,CT,NG,GAS,5004417000,...,54371640,0,53116114,Mcf,3.180741e+06,2.885549e+06,NaN,NaN,NaN,NaN
2,3,2013,Barry,AL,ELECTRIC POWER,1,ST,BIT,COAL,4962411861,...,51202482,0,2417558,Tons,5.263615e+06,4.775120e+06,NaN,NaN,NaN,NaN
3,3,2013,Barry,AL,ELECTRIC POWER,1,ST,NG,GAS,116829139,...,1206368,0,1178044,Mcf,7.057253e+04,6.402298e+04,NaN,NaN,NaN,NaN
4,7,2013,Gadsden,AL,ELECTRIC POWER,1,ST,BIT,COAL,82694496,...,1261795,0,52109,Tons,1.297125e+05,1.176744e+05,NaN,NaN,NaN,NaN

In [14]:
# Ensure nothing looks out of place with the imported dataframe

df.tail()

,Plant Code,Year,Plant Name,State,Sector Group,Sector Code,Prime Mover,Fuel Code,Aggregated Fuel Group,Generation (kWh),...,Fuel Consumption for Electric Generation (MMBtu),\n Fuel Consumption for Useful Thermal Output (MMBtu),Quantity of Fuel Consumed,Fuel Units,Tons of CO2 Emissions,Metric Tonnes of CO2 Emissions,NERC Region,Balancing Authority Code,Balancing Authority Name,EIA Balancing Authority Region
5312,63826,2019,POET Biorefining - Jewell,IA,INDUSTRIAL,7,ST,NG,GAS,19608000,...,223010,911468,1090844,Mcf,66366.499793,60207.293652,MRO,MISO,"Midcontinent Independent System Operator, Inc.",Midwest
5313,63829,2019,"POET Biorefining - Marion, LLC",OH,INDUSTRIAL,7,ST,NG,GAS,30509000,...,346988,1588619,1861160,Mcf,113232.219192,102723.595384,RFC,PJM,"PJM Interconnection, LLC",Mid-Atlantic
5314,63831,2019,"POET Biorefining Caro, LLC",MI,INDUSTRIAL,7,ST,NG,GAS,17681160,...,207313,380203,564919,Mcf,34369.446117,31179.756978,RFC,MISO,"Midcontinent Independent System Operator, Inc.",Midwest
5315,63832,2019,"POET Biorefining-Hanlontown, LLC",IA,INDUSTRIAL,7,ST,NG,GAS,16792000,...,190981,1041638,1185211,Mcf,72107.708222,65415.683772,MRO,MISO,"Midcontinent Independent System Operator, Inc.",Midwest
5316,63918,2019,POET Biorefining - Hudson,SD,INDUSTRIAL,7,ST,NG,GAS,12421000,...,141268,846349,949633,Mcf,57775.191256,52413.309676,MRO,MISO,"Midcontinent Independent System Operator, Inc.",Midwest

In [15]:
# Check how many rows and columns the data set has

df.shape

(38278, 22)

In [16]:
# Review the dataframe info: index dtype and columns, non-null values and memory usage

df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38278 entries, 0 to 5316
Data columns (total 22 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Plant Code                                            38278 non-null  int64
 1   Year                                                  38278 non-null  int64
 2   Plant Name                                            38278 non-null  object
 3   State                                                 38278 non-null  object
 4   Sector Group                                          38278 non-null  object
 5   Sector Code                                           38278 non-null  int64
 6   Prime Mover                                           38278 non-null  object
 7   Fuel Code                                             38278 non-null  object
 8   Aggregated Fuel Group                                 38278 non-null  object
 9   Generation (kWh)                                      38278 non-null  int64
 10  Useful Thermal Output (MMBtu)                         38278 non-null  int64
 11  Total Fuel Consumption (MMBtu)                        38278 non-null  int64
 12  Fuel Consumption for Electric Generation (MMBtu)      38278 non-null  int64
 13
 Fuel Consumption for Useful Thermal Output (MMBtu)  38278 non-null  int64
 14  Quantity of Fuel Consumed                             38278 non-null  object
 15  Fuel Units                                            37810 non-null  object
 16  Tons of CO2 Emissions                                 38278 non-null  float64
 17  Metric Tonnes of CO2 Emissions                        38278 non-null  float64
 18  NERC Region                                           21437 non-null  object
 19  Balancing Authority Code                              20762 non-null  object
 20  Balancing Authority Name                              21480 non-null  object
 21  EIA Balancing Authority Region                        21480 non-null  object
dtypes: float64(2), int64(8), object(12)
memory usage: 6.7+ MB

### 3. Data Cleaning

In [17]:
# Check whether the dataframe contains any mixed-type columns

for col in df.columns.tolist():
    weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (df[weird]) > 0: print (col)

Quantity of Fuel Consumed
Fuel Units
NERC Region
Balancing Authority Code
Balancing Authority Name
EIA Balancing Authority Region

In [18]:
# Check whether the dataframe has any missing values and count how many there are in each column

df.isnull().sum()

Plant Code                                                   0
Year                                                         0
Plant Name                                                   0
State                                                        0
Sector Group                                                 0
Sector Code                                                  0
Prime Mover                                                  0
Fuel Code                                                    0
Aggregated Fuel Group                                        0
Generation (kWh)                                             0
Useful Thermal Output (MMBtu)                                0
Total Fuel Consumption (MMBtu)                               0
Fuel Consumption for Electric Generation (MMBtu)             0
\n Fuel Consumption for Useful Thermal Output (MMBtu)        0
Quantity of Fuel Consumed                                    0
Fuel Units                                                 468
Tons of CO2 Emissions                                        0
Metric Tonnes of CO2 Emissions                               0
NERC Region                                              16841
Balancing Authority Code                                 17516
Balancing Authority Name                                 16798
EIA Balancing Authority Region                           16798
dtype: int64

In [19]:
# Calculate the percentage of missing values
# Fuel Units = 265, NERC Region = 43, Balancing Authority Code = 718
# The 1026 missing rows are just 4.78% of the total, 
# but we don't yet know the total CO2 emissions percentage yet
# so, these rows will be kept for now, and be given the value "unknown"

x = round(((265+43+718) / 21480 * 100), 2)
y = '%'
print("{0}{1}".format(x, y))

4.78%

In [14]:
# Replace each "NaN" with "unknown"

df = df.fillna('unknown')

In [15]:
# Check for full duplicates within the cleaned dataframe

df_duplicates = df[df.duplicated()]

In [16]:
# Check the "shape" to see if there is any duplicate rows

df_duplicates.shape

(0, 22)

In [17]:
# Replace overly long column names (inplace = True)

df.rename(
   columns = {
               'Fuel Consumption for Electric Generation (MMBtu)' : 'Fuel Use(generate electric MMBtu)',
               '\n Fuel Consumption for Useful Thermal Output (MMBtu)' : 'Fuel Use(useful thermal output MMBtu)',
               'Metric Tonnes of CO2 Emissions' : 'CO2 Emissions Metric Tonnes',
               'Quantity of Fuel Consumed' : 'Fuel Consumed Qty',
               'Total Fuel Consumption (MMBtu)' : 'Total Fuel Use (MMBtu)'
   },
   inplace = True)

In [18]:
# Review the dataframe info: index dtype and columns, non-null values and memory usage

df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21480 entries, 0 to 5316
Data columns (total 22 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Plant Code                             21480 non-null  int64
 1   Year                                   21480 non-null  int64
 2   Plant Name                             21480 non-null  object
 3   State                                  21480 non-null  object
 4   Sector Group                           21480 non-null  object
 5   Sector Code                            21480 non-null  int64
 6   Prime Mover                            21480 non-null  object
 7   Fuel Code                              21480 non-null  object
 8   Aggregated Fuel Group                  21480 non-null  object
 9   Generation (kWh)                       21480 non-null  int64
 10  Useful Thermal Output (MMBtu)          21480 non-null  int64
 11  Total Fuel Use (MMBtu)                 21480 non-null  int64
 12  Fuel Use(generate electric MMBtu)      21480 non-null  int64
 13  Fuel Use(useful thermal output MMBtu)  21480 non-null  int64
 14  Fuel Consumed Qty                      21480 non-null  int64
 15  Fuel Units                             21480 non-null  object
 16  Tons of CO2 Emissions                  21480 non-null  float64
 17  CO2 Emissions Metric Tonnes            21480 non-null  float64
 18  NERC Region                            21480 non-null  object
 19  Balancing Authority Code               21480 non-null  object
 20  Balancing Authority Name               21480 non-null  object
 21  EIA Balancing Authority Region         21480 non-null  object
dtypes: float64(2), int64(9), object(11)
memory usage: 3.8+ MB

In [19]:
# Check the basic statistics for the first 4 continuous variables to see if there are any obvious irregularities

df_stats1 = df.groupby('Sector Group').agg({
    'Generation (kWh)': ['min', 'max', 'mean', 'median'],
    'Useful Thermal Output (MMBtu)': ['min', 'max', 'mean'],
    'Total Fuel Use (MMBtu)': ['min', 'max', 'mean'],
    'Fuel Use(generate electric MMBtu)': ['min', 'max', 'mean']
}).style.format('{0:,.0f}').highlight_max(color='lightgreen')

In [20]:
# Review the basic statistics for the first 4 continuous variables

df_stats1

In [21]:
# Check the basic statistics for the next 4 continuous variables to see if there are any obvious irregularities

df_stats2 = df.groupby('Sector Group').agg({
    'Fuel Use(useful thermal output MMBtu)': ['min', 'max', 'mean', 'median'],
    'Fuel Consumed Qty': ['min', 'max', 'mean', 'median'],
    'Tons of CO2 Emissions': ['min', 'max', 'mean', 'median'],
    'CO2 Emissions Metric Tonnes': ['min', 'max', 'mean', 'median']
}).style.format('{0:,.0f}').highlight_max(color='lightgreen')

In [22]:
# Review the basic statistics for the next 4 continuous variables

df_stats2

In [23]:
# Check the basic statistics for the first 4 continuous variables by "Year"

df_stats3_year = df.groupby('Year').agg({
    'Generation (kWh)': ['min', 'max', 'mean', 'median'],
    'Useful Thermal Output (MMBtu)': ['min', 'max', 'mean'],
    'Total Fuel Use (MMBtu)': ['min', 'max', 'mean'],
    'Fuel Use(generate electric MMBtu)': ['min', 'max', 'mean']
}).style.format('{0:,.0f}').highlight_max(color='lightgreen')

In [24]:
# Review the basic statistics for the first 4 continuous variables by "Year"

df_stats3_year

In [25]:
# Check the basic statistics for the next 4 continuous variables by "Year"

df_stats4_year = df.groupby('Year').agg({
    'Fuel Use(useful thermal output MMBtu)': ['min', 'max', 'mean', 'median'],
    'Fuel Consumed Qty': ['min', 'max', 'mean', 'median'],
    'Tons of CO2 Emissions': ['min', 'max', 'mean', 'median'],
    'CO2 Emissions Metric Tonnes': ['min', 'max', 'mean', 'median']
}).style.format('{0:,.0f}').highlight_max(color='lightgreen')

In [26]:
# Review the basic statistics for the next 4 continuous variables by "Year"

df_stats4_year

In [27]:
# Capitalize each word in "Sector Group" column for better readability

df['Sector Group'] = df['Sector Group'].str.title()

In [28]:
df.head(50)

,Plant Code,Year,Plant Name,State,Sector Group,Sector Code,Prime Mover,Fuel Code,Aggregated Fuel Group,Generation (kWh),...,Fuel Use(generate electric MMBtu),Fuel Use(useful thermal output MMBtu),Fuel Consumed Qty,Fuel Units,Tons of CO2 Emissions,CO2 Emissions Metric Tonnes,NERC Region,Balancing Authority Code,Balancing Authority Name,EIA Balancing Authority Region
0,3,2016,Barry,AL,Electric Power,1,CA,NG,GAS,2918277000,...,895285,0,878457,Mcf,52374.0,47513.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
1,3,2016,Barry,AL,Electric Power,1,CT,NG,GAS,5483083000,...,57790622,0,56694492,Mcf,3380728.0,3066976.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
2,3,2016,Barry,AL,Electric Power,1,ST,BIT,COAL,4278313064,...,43137858,0,2044002,Tons,4436536.0,4024799.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
3,3,2016,Barry,AL,Electric Power,1,ST,NG,GAS,91217936,...,926020,0,908006,Mcf,54172.0,49144.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
4,7,2016,Gadsden,AL,Electric Power,1,ST,NG,GAS,190978000,...,2207718,404532,2570783,Mcf,152816.0,138633.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
5,8,2016,Gorgas,AL,Electric Power,1,ST,BIT,COAL,5481975915,...,53420676,0,2226626,Tons,5494077.0,4984194.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
6,8,2016,Gorgas,AL,Electric Power,1,ST,DFO,PET,12465085,...,125698,0,21722,Barrels,10137.0,9196.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
7,9,2016,Copper,TX,Electric Power,1,GT,NG,GAS,33073000,...,546763,0,522718,Mcf,31985.0,29017.0,WECC,EPE,El Paso Electric Company,Southwest
8,10,2016,Greene County,AL,Electric Power,1,GT,NG,GAS,156837001,...,2054244,0,1991576,Mcf,120172.0,109020.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
9,10,2016,Greene County,AL,Electric Power,1,GT,DFO,PET,5999,...,75,0,13,Barrels,6.0,5.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
10,10,2016,Greene County,AL,Electric Power,1,ST,BIT,COAL,525671207,...,5329105,0,234982,Tons,548075.0,497210.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
11,10,2016,Greene County,AL,Electric Power,1,ST,NG,GAS,627119793,...,7047509,0,6830383,Mcf,412276.0,374015.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
12,26,2016,E C Gaston,AL,Electric Power,1,GT,DFO,PET,132000,...,3267,0,563,Barrels,263.0,239.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
13,26,2016,E C Gaston,AL,Electric Power,1,ST,BIT,COAL,3774469502,...,39353677,0,1691020,Tons,4047349.0,3671731.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
14,26,2016,E C Gaston,AL,Electric Power,1,ST,NG,GAS,505818498,...,5365328,0,5211436,Mcf,313869.0,284741.0,SERC,SOCO,"Southern Company Services, Inc. - Trans",Southeast
15,30,2016,Madelia,MN,Electric Power,1,IC,DFO,PET,-163000,...,484,0,78,Barrels,39.0,35.0,MRO,MISO,Midcontinent Independent Transmission System O...,Midwest
16,47,2016,Colbert,AL,Electric Power,1,GT,NG,GAS,1938108,...,57802,0,56726,Mcf,3381.0,3068.0,SERC,TVA,Tennessee Valley Authority,Tennessee Valley Authority
17,47,2016,Colbert,AL,Electric Power,1,GT,DFO,PET,441892,...,13249,0,2286,Barrels,1068.0,969.0,SERC,TVA,Tennessee Valley Authority,Tennessee Valley Authority
18,47,2016,Colbert,AL,Electric Power,1,ST,BIT,COAL,739246850,...,8531305,0,392404,Tons,877407.0,795978.0,SERC,TVA,Tennessee Valley Authority,Tennessee Valley Authority
19,47,2016,Colbert,AL,Electric Power,1,ST,DFO,PET,2706150,...,31373,0,5409,Barrels,2530.0,2295.0,SERC,TVA,Tennessee Valley Authority,Tennessee Valley Authority
20,51,2016,Dolet Hills,LA,Electric Power,1,ST,LIG,COAL,3367664589,...,39127908,0,2851744,Tons,4213907.0,3822831.0,SPP,MISO,Midcontinent Independent Transmission System O...,Midwest
21,51,2016,Dolet Hills,LA,Electric Power,1,ST,NG,GAS,17252411,...,200841,0,192149,Mcf,11749.0,10659.0,SPP,MISO,Midcontinent Independent Transmission System O...,Midwest
22,54,2016,J K Smith,KY,Electric Power,1,GT,NG,GAS,222766040,...,2866450,0,2689112,Mcf,167686.0,152124.0,SERC,PJM,"PJM Interconnection, LLC",Mid-Atlantic
23,54,2016,J K Smith,KY,Electric Power,1,GT,DFO,PET,656960,...,8723,0,1499,Barrels,703.0,638.0,SERC,PJM,"PJM Interconnection, LLC",Mid-Atlantic
24,56,2016,Charles R Lowman,AL,Electric Power,1,ST,BIT,COAL,1470743544,...,16717799,0,723764,Tons,1719351.0,1559785.0,SERC,AEC,PowerSouth Energy Cooperative,Southeast
25,56,2016,Charles R Lowman,AL,Electric Power,1,ST,DFO,PET,9948456,...,114436,0,20806,Barrels,9229.0,8372.0,SERC,AEC,PowerSouth Energy Cooperative,Southeast
26,59,2016,Platte,NE,Electric Power,1,ST,SUB,COAL,495323639,...,5601828,0,333002,Tons,600205.0,544503.0,MRO,SWPP,Southwest Power Pool,Central
27,59,2016,Platte,NE,Electric Power,1,ST,DFO,PET,436361,...,4944,0,841,Barrels,399.0,362.0,MRO,SWPP,Southwest Power Pool,Central
28,60,2016,Whelan Energy Center,NE,Electric Power,1,ST,RC,COAL,1217144834,...,13650920,0,827458,Tons,1403936.0,1273642.0,MRO,SWPP,Southwest Power Pool,Central
29,60,2016,Whelan Energy Center,NE,Electric Power,1,ST,SUB,COAL,34574356,...,401148,0,24237,Tons,42981.0,38992.0,MRO,SWPP,Southwest Power Pool,Central
30,60,2016,Whelan Energy Center,NE,Electric Power,1,ST,DFO,PET,1978810,...,23400,0,4067,Barrels,1887.0,1712.0,MRO,SWPP,Southwest Power Pool,Central
31,63,2016,Gold Creek,AK,Electric Power,1,IC,DFO,PET,8000,...,114,0,20,Barrels,9.0,8.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
32,64,2016,Lemon Creek,AK,Electric Power,1,GT,DFO,PET,132000,...,2468,0,432,Barrels,199.0,181.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
33,64,2016,Lemon Creek,AK,Electric Power,1,IC,DFO,PET,80000,...,892,0,156,Barrels,72.0,65.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
34,66,2016,Skagway,AK,Electric Power,1,IC,DFO,PET,81000,...,1921,0,330,Barrels,155.0,141.0,unknown,unknown,Balancing Authority Not Reported,Alaska
35,69,2016,Haines,AK,Electric Power,1,IC,DFO,PET,-201000,...,1235,0,212,Barrels,100.0,90.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
36,75,2016,Anchorage 1,AK,Electric Power,1,GT,NG,GAS,45041386,...,544835,0,539441,Mcf,31873.0,28915.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
37,75,2016,Anchorage 1,AK,Electric Power,1,GT,DFO,PET,40614,...,491,0,89,Barrels,40.0,36.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
38,75,2016,Anchorage 1,AK,Electric Power,1,IC,DFO,PET,0,...,82,0,14,Barrels,7.0,6.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
39,79,2016,Aurora Energy LLC Chena,AK,Electric Power,3,ST,SUB,COAL,191982000,...,2415639,1021627,224722,Tons,368284.0,334105.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
40,85,2016,S W Bailey,AK,Electric Power,1,IC,DFO,PET,-1111000,...,7757,0,1333,Barrels,626.0,568.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
41,87,2016,Escalante,NM,Electric Power,1,ST,SUB,COAL,1298589130,...,14276083,0,786070,Tons,1529604.0,1387648.0,WECC,WACM,Western Area Power Administration - Rocky Moun...,Northwest
42,87,2016,Escalante,NM,Electric Power,1,ST,NG,GAS,3000870,...,33553,0,32310,Mcf,1963.0,1781.0,WECC,WACM,Western Area Power Administration - Rocky Moun...,Northwest
43,90,2016,Snake River,AK,Electric Power,1,IC,DFO,PET,30159000,...,257809,0,44450,Barrels,20791.0,18861.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
44,91,2016,Petersburg,AK,Electric Power,1,IC,DFO,PET,110740,...,1240,0,214,Barrels,100.0,91.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
45,92,2016,Seward (AK),AK,Electric Power,1,IC,DFO,PET,105000,...,1753,0,302,Barrels,141.0,128.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
46,95,2016,Wrangell,AK,Electric Power,1,IC,DFO,PET,44000,...,667,0,121,Barrels,54.0,49.0,ASCC,unknown,Balancing Authority Not Reported,Alaska
47,96,2016,Beluga,AK,Electric Power,1,GT,NG,GAS,84421000,...,1538083,0,1538083,Mcf,89977.0,81627.0,ASCC,unknown,Chugach Electric Assn Inc,Alaska
48,99,2016,Frederickson,WA,Electric Power,1,GT,NG,GAS,19473787,...,536850,0,523758,Mcf,31406.0,28491.0,WECC,PSEI,Puget Sound Energy,Northwest
49,99,2016,Frederickson,WA,Electric Power,1,GT,DFO,PET,213,...,6,0,1,Barrels,0.0,0.0,WECC,PSEI,Puget Sound Energy,Northwest

In [29]:
# Review the shape

df.shape

(21480, 22)

In [30]:
# Export cleaned dataframe to pkl

#df.to_pickle(os.path.join(path2, '03 Scripts','Prepared Data', 'emissions2016-2019-clean.pkl'))

In [31]:
# Export cleaned dataframe to csv
#df.to_csv(os.path.join(path2, '03 Scripts','Prepared Data', 'emissions2016-2019-clean.csv'))